select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select 	customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating),2) as "AVG Product Rating" from customer
group by item_purchased
order by avg(review_rating) DESC
Limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type, Round(avg(purchase_amount),2) from customer where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, 
Count(customer_id) as total_customers, 
Round(Sum(purchase_amount),2) as total_revenue,
Round(AVG(purchase_amount),2) as avg_spend 
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
Round (sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100, 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
Limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
With customer_type as (
select customer_id, previous_purchases,
CASE
when previous_purchases = 1 then 'New'
When previous_purchases between 2 and 10 then 'Returning'
Else 'Loyal' End as customer_segment
from customer
)
Select customer_Segment, Count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_Count as (
select category, item_purchased,
Count(customer_id) as total_orders,
Row_number() over(partition by category order by Count(customer_id)DESC) as item_rank
from customer 
group by category, item_purchased
) 
Select item_rank, category, item_purchased, total_orders
from item_Count
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
Select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

